### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by mbonokezia** [skye8-tech/stocka-inventory-management-system#2]
this issue is assigned to @Ngochi.
clone the repository to your local device and create a branch called pages/profile.
work on the assigned page .
Also work on the signup and signup-error page. Follow the same process.
stage your work, commit and create a pull request to close the issue.
use the required languages

**Comment by Ngochi-N** [comment]
I have completed the profile page.
![shot of the profile page](https://github.com/user-attachments/assets/a69b7c53-6dcd-4247-ae30-57d607a6f690)

**Comment by Ngochi-N** [comment]
I have completed working on the profile page
